site_name: Journée de rentrée 2025 de l'équipe de probabilités - IMT
theme:
  name: material
  logo : assets/imt.jpg


extra_css:
  - stylesheets/style.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
